name: Continuous Integration

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    name: PHPUnit
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: [ '8.1' ]
        mediawiki: [ REL1_43 ]
    steps:
      - name: Setup Extension
        uses: actions/checkout@v4
      - name: Mediawiki PHPUnit
        uses: wikiteq/mediawiki-phpunit-action@master
        with:
          type: extension
          php: ${{ matrix.php }}
          mwbranch: ${{ matrix.mediawiki }}
          extension: BulkBlock